all_joints:
- - 0
- - 1
- - 2
- - 3
all_joints_names:
- Index_Left
- Index_Right
- Hand_Left
- Hand_Right
alpha_r: 0.02
apply_prob: 0.5
batch_size: 1
clahe: true
claheratio: 0.1
cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_BrailleJul26/Braille_Priyank
  Namdev95shuffle1.mat
dataset_type: imgaug
decay_steps: 30000
display_iters: 1000
edge: false
emboss:
  alpha:
  - 0.0
  - 1.0
  embossratio: 0.1
  strength:
  - 0.5
  - 1.5
global_scale: 0.8
histeq: true
histeqratio: 0.1
# init_weights: /Users/priyanknamdev/opt/anaconda3/envs/DEEPLABCUT_M1/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/mobilenet_v2_1.0_224.ckpt
init_weights: /Users/priyanknamdev/My Data/Maynooth University/Thesis Dissertation/Coding/Data/Brail/04/Braille-Priyank Namdev-2022-07-26/dlc-models/iteration-0/BrailleJul26-trainset95shuffle1/train/snapshot-30000
intermediate_supervision: false
intermediate_supervision_layer: 12
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
lr_init: 0.0005
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_BrailleJul26/Documentation_data-Braille_95shuffle1.pickle
min_input_size: 64
mirror: false
multi_stage: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: mobilenet_v2_1.0
num_joints: 4
pairwise_huber_loss: false
pairwise_predict: false
partaffinityfield_predict: false
pos_dist_thresh: 17
project_path: /Users/priyanknamdev/My Data/Maynooth University/Thesis Dissertation/Coding/Data/Brail/04/Braille-Priyank
  Namdev-2022-07-26
rotation: 25
rotratio: 0.4
save_iters: 50000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
sharpen: false
sharpenratio: 0.3
